---
baseURL: https://github.com/Qskotlv/Pika.github.io/
languageCode: en-us
title: 3AGameTech Course
theme: piko
themeDir: themes/
paginate: "16"
copyright: JackSquirrel
canonifyURLs: true
googleAnalytics: # Enter Google Analytics ie. UA-012345678-9
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
outputs:
  home:
  - HTML
  - RSS
  - JSON
minify:
  disableCSS: false
  disableHTML: false
  disableJS: false
  disableJSON: false
  disableSVG: false
  disableXML: false
  minifyOutput: true
  tdewolff:
    html:
      keepWhitespace: false

params:
  analytics:
    google:
      SiteVerificationTag: # Google Site Verification
    yandex:
      SiteVerificationTag: # Yandex Site Verification
    bing:
      SiteVerificationTag: # Bing Site Verification
  env: production
  author: Your Name
  description: Your website description
  math: false
  images:
  - "title.png"
  label:
    title: _3A开放大世界游戏引擎全能课_
    text: Welcome to Piko
    icon: zap.svg
    iconHeight: "35"
    iconWIdth: "35"
  comments: true
  mainSections:
  - blog
  ShowShareButtons: true
  ShowCodeCopyButtons: true
  ShowRelated: true
  CookieNotice: We use cookies to improve your experience on our site and to show
    you relevant advertising.
  CookieLink: /legal/privacy/#cookies-and-web-beacons
  CookieButton: Cookies Policy
  disableAnchoredHeadings: false
  contactFormAction: # Get link from https://formsubmit.io or https://fabform.io
  assets:
    disableFingerprinting: false
    favicon: zap.svg
    favicon16x16: zap.svg
    favicon32x32: zap.svg
    apple_touch_icon: zap.svg
    safari_pinned_tab: zap.svg
  ShowReadingTime: true
  ShowBreadCrumbs: true
  homepage:
    # Hero Section
    disableHeroSection: false
    heroUpperTitle: 
    heroTitle: 3A大世界游戏引擎全能课
    heroDescription: 欢迎来到........
    heroCTAPrimaryText: 报名参加课程
    #heroCTAPrimaryUrl: "http://littlepaypay.fun/"
    heroCTAPrimaryUrl: "/blog/"
    heroCTASecondaryText: 咨询客服
    heroCTASecondaryUrl: "/contact/"
    heroBackgroundImage: "title.png"

    # Blog Section
    disableBlogSection: false
    blogTitle: About this course
    blogDescription: progress
    seeMoreText: More Posts


    # About Section    
    disableAboutSection: false
    aboutTitle: About
    aboutDescription: Just something about me
    aboutImgUrl: "aboutme.jpg"
    aboutContent: Hi, I'm JackSquirrel, the instructor for this course.



    # Portfolio Section
    disablePortfolioSection: false
    portfolioTitle: Showcase
    portfolioDescription: 展示
    portfolio:
    - imageUrl: introduction.png
      alt: # image alt for better SEO
      description: 参考图1
      websiteUrl: #
    - imageUrl: shader.png
      alt: # image alt for better SEO
      description: 参考图2
      websiteUrl: #
    - imageUrl: blueprint.png
      alt: # image alt for better SEO
      description: 参考图3
      websiteUrl: #
    - imageUrl: building.png
      alt: # image alt for better SEO
      description: 参考图4
      websiteUrl: #
    - imageUrl: grass.jpg
      alt: # image alt for better SEO
      description: 参考图5
      websiteUrl: #
    - imageUrl: forest1.png
      alt: # image alt for better SEO
      description: 参考图6
      websiteUrl: #          
    - imageUrl: terrain.png
      alt: # image alt for better SEO
      description: 参考图7
      websiteUrl: #             
    - imageUrl: lighting.png
      alt: # image alt for better SEO
      description: 参考图8
      websiteUrl: #  
    - imageUrl: gi.png
      alt: # image alt for better SEO
      description: 参考图9
      websiteUrl: #       
    - imageUrl: shadow.jpg
      alt: # image alt for better SEO
      description: 参考图10
      websiteUrl: #  
    - imageUrl: chunk.png
      alt: # image alt for better SEO
      description: 参考图11
      websiteUrl: # 
    - imageUrl: rtx.png
      alt: # image alt for better SEO
      description: 参考图12
      websiteUrl: # 
    - imageUrl: openworld.png
      alt: # image alt for better SEO
      description: 参考图13
      websiteUrl: # 
    - imageUrl: 233.png
      alt: # image alt for better SEO
      description: 参考图14
      websiteUrl: # 


  # Search Options (https://fusejs.io/)
  plugins:
    css:
    - link: plugins/css/pico.min.css
    js:
    - link: plugins/js/feather.min.js
