---
baseURL: https://github.com/Qskotlv/Pika.github.io/
languageCode: en-us
title: Piko
theme: piko
themeDir: themes/
paginate: "16"
copyright: A template by [Heksagon](https://www.heksagon.net "Your most friendly developer")
canonifyURLs: true
googleAnalytics: # Enter Google Analytics ie. UA-012345678-9
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
outputs:
  home:
  - HTML
  - RSS
  - JSON
minify:
  disableCSS: false
  disableHTML: false
  disableJS: false
  disableJSON: false
  disableSVG: false
  disableXML: false
  minifyOutput: true
  tdewolff:
    html:
      keepWhitespace: false

params:
  analytics:
    google:
      SiteVerificationTag: # Google Site Verification
    yandex:
      SiteVerificationTag: # Yandex Site Verification
    bing:
      SiteVerificationTag: # Bing Site Verification
  env: production
  author: Your Name
  description: Your website description
  math: false
  images:
  - "og.webp"
  label:
    title: _Piko Title_
    text: Welcome to Piko
    icon: zap.svg
    iconHeight: "35"
    iconWIdth: "35"
  comments: true
  mainSections:
  - blog
  ShowShareButtons: true
  ShowCodeCopyButtons: true
  ShowRelated: true
  CookieNotice: We use cookies to improve your experience on our site and to show
    you relevant advertising.
  CookieLink: /legal/privacy/#cookies-and-web-beacons
  CookieButton: Cookies Policy
  disableAnchoredHeadings: false
  contactFormAction: # Get link from https://formsubmit.io or https://fabform.io
  assets:
    disableFingerprinting: false
    favicon: zap.svg
    favicon16x16: zap.svg
    favicon32x32: zap.svg
    apple_touch_icon: zap.svg
    safari_pinned_tab: zap.svg
  ShowReadingTime: true
  ShowBreadCrumbs: true
  homepage:
    # Hero Section
    disableHeroSection: false
    heroUpperTitle: 
    heroTitle: Piko
    heroDescription: Lightweight theme for your every need
    heroCTAPrimaryText: Blog
    heroCTAPrimaryUrl: "/blog/"
    heroCTASecondaryText: Contact Me
    heroCTASecondaryUrl: "/contact/"
    heroBackgroundImage: "portfolio-1.webp"
    # Blog Section
    disableBlogSection: false
    blogTitle: Latest Posts
    blogDescription: This is my latest blog posts
    seeMoreText: More Posts
    # About Section    
    disableAboutSection: false
    aboutTitle: About
    aboutDescription: Just something about me
    aboutImgUrl: "jacksquirrel.jpg"
    aboutContent: Hi guys. This is where you put something about yourself.


    # Portfolio Section
    disablePortfolioSection: false
    portfolioTitle: Showcase
    portfolioDescription: 作品展示
    portfolio:
    - imageUrl: introduction.png
      alt: # image alt for better SEO
      description: Portfolio 1231244.
      websiteUrl: #
    - imageUrl: shader.png
      alt: # image alt for better SEO
      description: Portfolio Two.
      websiteUrl: #
    - imageUrl: dots.png
      alt: # image alt for better SEO
      description: Portfolio Three.
      websiteUrl: #
    - imageUrl: building.png
      alt: # image alt for better SEO
      description: Portfolio Three.
      websiteUrl: #
    - imageUrl: grass.jpg
      alt: # image alt for better SEO
      description: Portfolio Three.
      websiteUrl: #
    - imageUrl: forest.png
      alt: # image alt for better SEO
      description: Portfolio Three.
      websiteUrl: #          
    - imageUrl: terrain1.png
      alt: # image alt for better SEO
      description: Portfolio Three.
      websiteUrl: #             
    - imageUrl: lighting.png
      alt: # image alt for better SEO
      description: Portfolio Three.
      websiteUrl: #  
    - imageUrl: gi.png
      alt: # image alt for better SEO
      description: Portfolio Three.
      websiteUrl: #       
    - imageUrl: shadow.jpg
      alt: # image alt for better SEO
      description: Portfolio Three.
      websiteUrl: #  
    - imageUrl: portfolio-2.webp
      alt: # image alt for better SEO
      description: Portfolio Three.
      websiteUrl: # 
    - imageUrl: rtx.png
      alt: # image alt for better SEO
      description: Portfolio Three.
      websiteUrl: # 
    - imageUrl: hdr4k.jpg
      alt: # image alt for better SEO
      description: Portfolio Three.
      websiteUrl: # 
    - imageUrl: nanite.png
      alt: # image alt for better SEO
      description: Portfolio Three.
      websiteUrl: # 


  # Search Options (https://fusejs.io/)
  plugins:
    css:
    - link: plugins/css/pico.min.css
    js:
    - link: plugins/js/feather.min.js
